chore(containers): add docker and compose support to project
lucas-a-pelegrino/node-bloodboiler-sequelized pull request #59
Opened 2020-12-23 20:12 UTC by btd1337

implements #57

branch has been changed to `develop`

2020-12-23 20:22 UTC, btd1337 commented
@lucas-a-pelegrino Fiz a alteração da branch pra `develop`.

Mas veja uma questão: 

A `CI` tá reportando que houve redução na cobertura em arquivos `.js`, mas se observar bem, essa `MR` apenas adiciona uma pasta `docker` contendo `dockerfiles` e um arquivo `docker-compose` na raiz. Outro ajuste foi no `Readme` e no `Package.json`. Nada que gere impacto nos arquivos `.js`, ou tem? Como tá funcionando essa checagem de cobertura?

---

Como a outra `MR` foi fechada, ficou [este comentário](https://github.com/lucas-a-pelegrino/node-bloodboiler-sequelized/pull/58#discussion_r548084623) pra você analisar.

Qualquer dúvida, me coloco a disposição 👍️

2020-12-24 00:52 UTC, lucas-a-pelegrino commented
@btd1337 Sobre o coverage, você rodou os testes na sua máquina local pra ver se tem o mesmo resultado? Se não, rode os testes em local e manda aqui o resultado.

-- 

[Respondi](https://github.com/lucas-a-pelegrino/node-bloodboiler-sequelized/pull/58#discussion_r548332676) seu comentário do outro PR também.

2020-12-24 01:02 UTC, lucas-a-pelegrino commented
Inclusive, dê uma olhada na implementação do Docker utlizada no [Bloodboiler](https://github.com/lucas-a-pelegrino/node-bloodboiler) para Mongo. Manter os padrões dentro da codebase do boilerplate é importante.

2020-12-24 17:59 UTC, btd1337 commented
> Inclusive, dê uma olhada na implementação do Docker utlizada no [Bloodboiler](https://github.com/lucas-a-pelegrino/node-bloodboiler) para Mongo. Manter os padrões dentro da codebase do boilerplate é importante.

Blz. Analisei o `Dockerfile` e gostaria apenas de fazer duas sugestões de melhoria:

1. Considere utilizar `Multi-Stage Builds` para otimizar e tornar mais seguras as camadas das suas imagens.

Leia os motivos aqui: 

https://itnext.io/using-multi-stage-docker-builds-for-speed-and-security-9d3a1cd9cd8c

https://baykara.medium.com/optimize-docker-image-via-multi-stage-builds-dd8e8ec796de

https://docs.docker.com/develop/develop-images/multistage-build/

---

2. Considere manter a arquitetura dos `Dockerfiles` dentro de uma pasta `docker`:

Uma das justificativas: É comum a utilização de mais de um `dockerfile` por projeto. Quando isso acontece, se torna necessário e trabalhoso o refatoramento da estrutura para essa que está montada: 

- Criar subpastas para cada um dos `dockerfiles`
- Alterar o `compose` para refletir os novos apontamentos

Utilizar uma boa arquitetura desde o início **evita retrabalhos**.

2020-12-24 19:58 UTC, lucas-a-pelegrino commented
> > Inclusive, dê uma olhada na implementação do Docker utlizada no [Bloodboiler](https://github.com/lucas-a-pelegrino/node-bloodboiler) para Mongo. Manter os padrões dentro da codebase do boilerplate é importante.
> 
> 
> 
> Blz. Analisei o `Dockerfile` e gostaria apenas de fazer duas sugestões de melhoria:
> 
> 
> 
> 1. Considere utilizar `Multi-Stage Builds` para otimizar e tornar mais seguras as camadas das suas imagens.
> 
> 
> 
> Leia os motivos aqui: 
> 
> 
> 
> https://itnext.io/using-multi-stage-docker-builds-for-speed-and-security-9d3a1cd9cd8c
> 
> 
> 
> https://baykara.medium.com/optimize-docker-image-via-multi-stage-builds-dd8e8ec796de
> 
> 
> 
> https://docs.docker.com/develop/develop-images/multistage-build/
> 
> 
> 
> ---
> 
> 
> 
> 2. Considere manter a arquitetura dos `Dockerfiles` dentro de uma pasta `docker`:
> 
> 
> 
> Uma das justificativas: É comum a utilização de mais de um `dockerfile` por projeto. Quando isso acontece, se torna necessário e trabalhoso o refatoramento da estrutura para essa que está montada: 
> 
> 
> 
> - Criar subpastas para cada um dos `dockerfiles`
> 
> - Alterar o `compose` para refletir os novos apontamentos
> 
> 
> 
> Utilizar uma boa arquitetura desde o início **evita retrabalhos**.
> 
> 
> 
> 

A ideia de utilizar multi stage é interessante sim.

Sobre a pasta **docker**, estou com planos de passar o que for relacionado a infraestrutura para uma pasta: `iac` **(infrastructure as code)** e organizar coisas como docker e outros scripts dentro dela.

Porém ainda estou estudando as possibilidades.

2020-12-25 00:35 UTC, eliasrabelomatos requested changes
Opa @lucas-a-pelegrino , dando uma olhada nesse pr que você solicitou review. Não vi antes ja que esse projeto deve ser tocado fora do horário de trabalho.

Cara eu ate dei uma lida na discussão, mas não vi e nem verei o código enviado pois está sendo acusado baixa de cóbertura. Erramos nesse sentido, devemos deixar mais explicito que não aceitaremos pr em hipótese alguma se o mesmo baixar a cobertura.

Sugiro o decline imediato do pr, onde o autor, caso deseje e cumpra os 100% de cobertura abra outro. Sugiro também que você solicite em propostas de PR que envolvam questões de arquiteturas como esse, a review também de contribuidores mais experiencia com decisões arquiteturais como Tiago Drumond, Rafael Tudela, Igor Baesse e Nelson Sinis.

Sugiro, por fim. Que o autor nao use force push.

2020-12-25 00:38 UTC, lucas-a-pelegrino commented
> Opa @lucas-a-pelegrino , dando uma olhada nesse pr que você solicitou review. Não vi antes ja que esse projeto deve ser tocado fora do horário de trabalho.
> 
> Cara eu ate dei uma lida na discussão, mas não vi e nem verei o código enviado pois está sendo acusado baixa de cóbertura. Erramos nesse sentido, devemos deixar mais explicito que não aceitaremos pr em hipótese alguma se o mesmo baixar a cobertura.
> 
> Sugiro o decline imediato do pr, onde o autor, caso deseje e cumpra os 100% de cobertura abra outro. Sugiro também que você solicite em propostas de PR que envolvam questões de arquiteturas como esse, a review também de contribuidores mais experientes com decisões arquiteturais como Tiago Drumond, Rafael Tudela, Igor Baesse e Nelson Sinis.
> 
> Sugiro, por fim. Que o autor nao use force push.

Agreed. 👍

2020-12-25 00:42 UTC, eliasrabelomatos commented
> > Opa @lucas-a-pelegrino , dando uma olhada nesse pr que você solicitou review. Não vi antes ja que esse projeto deve ser tocado fora do horário de trabalho.
> > Cara eu ate dei uma lida na discussão, mas não vi e nem verei o código enviado pois está sendo acusado baixa de cóbertura. Erramos nesse sentido, devemos deixar mais explicito que não aceitaremos pr em hipótese alguma se o mesmo baixar a cobertura.
> > Sugiro o decline imediato do pr, onde o autor, caso deseje e cumpra os 100% de cobertura abra outro. Sugiro também que você solicite em propostas de PR que envolvam questões de arquiteturas como esse, a review também de contribuidores mais experientes com decisões arquiteturais como Tiago Drumond, Rafael Tudela, Igor Baesse e Nelson Sinis.
> > Sugiro, por fim. Que o autor nao use force push.
> 
> Agreed. 👍

x

> > Opa @lucas-a-pelegrino , dando uma olhada nesse pr que você solicitou review. Não vi antes ja que esse projeto deve ser tocado fora do horário de trabalho.
> > Cara eu ate dei uma lida na discussão, mas não vi e nem verei o código enviado pois está sendo acusado baixa de cóbertura. Erramos nesse sentido, devemos deixar mais explicito que não aceitaremos pr em hipótese alguma se o mesmo baixar a cobertura.
> > Sugiro o decline imediato do pr, onde o autor, caso deseje e cumpra os 100% de cobertura abra outro. Sugiro também que você solicite em propostas de PR que envolvam questões de arquiteturas como esse, a review também de contribuidores mais experientes com decisões arquiteturais como Tiago Drumond, Rafael Tudela, Igor Baesse e Nelson Sinis.
> > Sugiro, por fim. Que o autor nao use force push.
> 
> Agreed. 👍

Já que você respondeu em inglês, me lembrou outra coisa. Sugiro aceitar apenas discussões em inglês pois desejamos que contribuidores ao redor do mundo possam ajudar.

2020-12-25 00:45 UTC, lucas-a-pelegrino commented
> > > Opa @lucas-a-pelegrino , dando uma olhada nesse pr que você solicitou review. Não vi antes ja que esse projeto deve ser tocado fora do horário de trabalho.
> > > Cara eu ate dei uma lida na discussão, mas não vi e nem verei o código enviado pois está sendo acusado baixa de cóbertura. Erramos nesse sentido, devemos deixar mais explicito que não aceitaremos pr em hipótese alguma se o mesmo baixar a cobertura.
> > > Sugiro o decline imediato do pr, onde o autor, caso deseje e cumpra os 100% de cobertura abra outro. Sugiro também que você solicite em propostas de PR que envolvam questões de arquiteturas como esse, a review também de contribuidores mais experientes com decisões arquiteturais como Tiago Drumond, Rafael Tudela, Igor Baesse e Nelson Sinis.
> > > Sugiro, por fim. Que o autor nao use force push.
> > 
> > 
> > Agreed. 👍
> 
> x
> 
> > > Opa @lucas-a-pelegrino , dando uma olhada nesse pr que você solicitou review. Não vi antes ja que esse projeto deve ser tocado fora do horário de trabalho.
> > > Cara eu ate dei uma lida na discussão, mas não vi e nem verei o código enviado pois está sendo acusado baixa de cóbertura. Erramos nesse sentido, devemos deixar mais explicito que não aceitaremos pr em hipótese alguma se o mesmo baixar a cobertura.
> > > Sugiro o decline imediato do pr, onde o autor, caso deseje e cumpra os 100% de cobertura abra outro. Sugiro também que você solicite em propostas de PR que envolvam questões de arquiteturas como esse, a review também de contribuidores mais experientes com decisões arquiteturais como Tiago Drumond, Rafael Tudela, Igor Baesse e Nelson Sinis.
> > > Sugiro, por fim. Que o autor nao use force push.
> > 
> > 
> > Agreed. 👍
> 
> Já que você respondeu em inglês, me lembrou outra coisa. Sugiro aceitar apenas discussões em inglês pois desejamos que contribuidores ao redor do mundo possam ajudar.

Boa!! Considerando todas as falhas reportadas no PR, acredito que o melhor seja fecha-lo.

2020-12-25 00:45 UTC, closed without merging